core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path("admin/", admin.site.urls),
    path('', include('admin_coreui.urls')),
]

klaim_registration/urls.py
from django.urls import path, re_path

from . import views
# from .views import nppAutoComplete

urlpatterns = [
    path('', views.index, name='home-klaim'),
    path('daftar/', views.tambahKlaim, name='add'),
    path('hrd/klaim/', views.daftarKlaimHRD,
         name='hrd-klaim'),
    # path('hrd1/klaim/',views.daftarKlaimHRD1, name='hrd1-klaim'),
    path('hrd/klaim/all/', views.get_klaimhrds_json, name='all-klaim'),

    path('hrd/klaim/<int:id>/', views.get_klaimhrd_json, name='klaim-detail'),
    # path('klaim/zip/<int:id>/', views.zipAll, name='zip-file'),
    # re_path(
    #     r'^npp-autocomplete/$',
    #     nppAutoComplete.as_view(),
    #     name='npp-autocomplete',
    # ),

]

klaim_registration/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

NIK_VALIDATOR = RegexValidator("^\d{16}$",
    "Format NIK Tidak Sesuai")

HP_VALIDATOR = RegexValidator("^(08+[1-9])([0-9]{7,9})$", "Format NO HP TIDAK SESUA!!!")

NO_REK_VALIDATOR = RegexValidator("^\d{6,}$", "No Rekening Harus Berupa Angka")

EKSTENSI_VALIDATOR = RegexValidator(".*\.(jpg|JPG|gif|GIF|doc|DOC|pdf|PDF)", "Only Support PDF dan JPG")

SEGMEN = (
    ('PU', 'PENERIMA UPAH'),
    ('BPU', 'BUKAN PENERIMA UPAH'),
    ('JAKON', 'JASA KONSTRUKSI'),
)

STATUS = (
    ('1','BELUM MENIKAH'),
    ('2','MENIKAH')
)

STATUS_APPROVAL = (
    ('DALAM PEMERIKSAAN','DALAM PEMERIKSAAN'),
    ('DISETUJUI','DISETUJUI'),
    ('DITOLAK','DITOLAK')
)

class Perusahaan(models.Model):
    nama = models.CharField(max_length=200)
    npp = models.CharField(max_length=8)

    class Meta:
        ordering = ['-npp']
        verbose_name = "NPP"
        verbose_name_plural = "LIST NPP"

    def __str__(self):
        return self.nama
    
class DataKlaim(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nama = models.CharField(max_length=200)
    nik = models.CharField(max_length=16, validators=[NIK_VALIDATOR])
    kpj = models.CharField(max_length=11)
    npp = models.ForeignKey(Perusahaan, on_delete=models.CASCADE)
    tgl_lahir = models.DateField()
    tempat_lahir = models.CharField(max_length=200)
    alamat = models.CharField(max_length=250)
    nama_ibu = models.CharField(max_length=100)
    status = models.CharField(choices=STATUS, max_length=1, default='1')
    nama_pasangan = models.CharField(max_length=100, null=True, blank=True)
    tgl_lahir_pasangan = models.DateField(blank=True, null=True)
    nama_anak_s = models.CharField(max_length=100, blank=True, null=True)
    tgl_lahir_s = models.DateField(null=True, blank=True)
    nama_anak_d = models.CharField(max_length=100, blank=True, null=True)
    tgl_lahir_d = models.DateField(null=True, blank=True)
    no_hp = models.CharField(max_length=15, validators=[HP_VALIDATOR])
    nama_rekening = models.CharField(max_length=100)
    no_rekening = models.CharField(max_length=16, validators=[NO_REK_VALIDATOR])
    file_kk = models.FileField(upload_to='kk/', validators=[EKSTENSI_VALIDATOR])
    file_ktp = models.FileField(upload_to='ktp/', validators=[EKSTENSI_VALIDATOR])
    file_buku_nikah = models.FileField(upload_to='buku-nikah/', validators=[EKSTENSI_VALIDATOR])
    file_lain = models.FileField(upload_to='lain/', null=True, blank=True, validators=[EKSTENSI_VALIDATOR])
    created_on = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = "DATA KLAIM"
        verbose_name_plural = "LIST DATA KLAIM"

    def __str__(self):
        return '{} - {}'.format(self.nik, self.nama)

class DaftarHRD(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nama = models.CharField(max_length=100)
    npp = models.ForeignKey(Perusahaan, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "LIST HRD"

    def __str__(self):
        return self.nama

class ApprovalHRD(models.Model):
    status = models.CharField(choices=STATUS_APPROVAL, default='DALAM PEMERIKSAAN', max_length=20)
    klaim = models.ForeignKey(DataKlaim, on_delete=models.CASCADE)
    hrd = models.ForeignKey(DaftarHRD, on_delete=models.CASCADE)
    keterangan = models.TextField(null=True, blank=True)

klaim_registration/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.db.models import Subquery, OuterRef, IntegerField
from django.http import JsonResponse
# from dal import autocomplete

from .form import DataKlaimForm
from .models import DataKlaim, Perusahaan, ApprovalHRD, DaftarHRD


@login_required(login_url='/accounts/login/')
def index(request):
    user = request.user

    is_admin = User.objects.filter(username=user, is_superuser=True)

    # is_hrd = DaftarHRD.objects.get(user=user)
    if is_admin:
        datas = DataKlaim.objects.all()
        size = datas.count()
    else:
        datas = DataKlaim.objects.filter(user=user).annotate(status_approve=Subquery(
            ApprovalHRD.objects.filter(klaim_id=OuterRef('pk')).values('status')[:1]))
        size = datas.count()
    context = {
        'datas': datas,
        'size': size,
    }

    return render(request, 'klaim_registration/index.html', context)


@login_required(login_url='/accounts/login/')
def tambahKlaim(request):
    user = request.user
    cekKlaim = ApprovalHRD.objects.filter(
        klaim__user__username=user, status='DISETUJUI')
    if cekKlaim.exists():
        messages.warning(request, "Akun anda sudah pernah mengajukan KLAIM")
        return redirect(reverse('home-klaim'))
    # print(user.is_authenticated)
    if request.method == 'POST':
        forms = DataKlaimForm(request.POST, request.FILES)
        if forms.is_valid():
            post = forms.save(commit=False)
            # post.user = user
            post.user = user

            # post.npp = request.POST['npp']
            post.save()
            hrd = DaftarHRD.objects.get(npp_id=post.npp_id)
            ApprovalHRD.objects.create(klaim_id=post.id, hrd_id=hrd.id)

            return redirect('home')

    else:
        forms = DataKlaimForm()
    return render(request, 'klaim_registration/daftar.html', {'forms': forms})


@login_required(login_url='/accounts/login/')
def daftarKlaimHRD(request):
    # print(request.user)
    datas = ApprovalHRD.objects.all().filter(
        hrd__user__username=request.user, status='DALAM PEMERIKSAAN')
    if not datas.exists():
        datas = ApprovalHRD.objects.all().filter(hrd__user__username=request.user)
        # detail = datas.select_related('klaim')
        # print(detail)
    if request.is_ajax:
        # print(request.POST.get('status'))
        ApprovalHRD.objects.filter(id=request.POST.get('id')).update(
            status=request.POST.get('status'), keterangan=request.POST.get('keterangan'))
        # return JsonResponse({'data': 'sucess'})
    context = {
        'datas': datas,
        # 'detail':detail,
    }

    return render(request, 'klaim_registration/hrd.html', context)


@login_required(login_url='/accounts/login/')
def daftarKlaimHRD1(request):
    # print(request.user)
    datas = ApprovalHRD.objects.all().filter(
        hrd__user__username=request.user, status='DALAM PEMERIKSAAN')
    if not datas.exists():
        datas = ApprovalHRD.objects.all().filter(hrd__user__username=request.user)
        detail = datas.select_related('klaim')
        # print(detail)
    if request.is_ajax:
        # print(request.POST.get('status'))
        ApprovalHRD.objects.filter(id=request.POST.get('id')).update(
            status=request.POST.get('status'), keterangan=request.POST.get('keterangan'))
        # return JsonResponse({'data': 'sucess'})
    context = {
        'datas': datas,
        'detail': detail,
    }

    return render(request, 'klaim_registration/hrd1.html', context)


@login_required(login_url='/accounts/login/')
def get_detail_tk(request, id=None):
    instance = get_object_or_404(DataKlaim, id=id)
    context = {
        'instance': instance
    }
    return render(request, 'klaim_registration/modal.html', context)


def get_klaimhrd_json(request, id):
    hrd_qs = list(ApprovalHRD.objects.all().filter(hrd__user__username=request.user, id=id).values(
        'id', 'klaim__nama', 'klaim__nik', 'klaim__kpj', 'klaim__npp', 'klaim__tempat_lahir', 'klaim__tgl_lahir',
        'klaim__nama_ibu', 'klaim__status', 'klaim__nama_rekening', 'klaim__no_rekening', 'klaim__no_hp'
    ))

    return JsonResponse({'data': hrd_qs})


def get_klaimhrds_json(request):
    hrd_qs = list(ApprovalHRD.objects.all().filter(hrd__user__username=request.user).values(
        'klaim_id', 'klaim__nama', 'klaim__nik', 'klaim__kpj', 'klaim__npp', 'klaim__tempat_lahir', 'klaim__tgl_lahir',
        'klaim__nama_ibu', 'klaim__status', 'klaim__nama_rekening', 'klaim__no_rekening', 'klaim__no_hp'
    ))

    return JsonResponse({'data': hrd_qs})


@login_required(login_url='/accounts/login/')
def daftarSeluruhKlaim(request):
    is_hrd = ApprovalHRD.objects.all().filter(
        hrd__user__username=request.user)[0]
    print(is_hrd)
    if is_hrd:
        datas = is_hrd.all()
        return render(request, 'klaim_registration/hrd.html', {'datas': datas})
    else:
        return redirect('home-klaim')


# def zipAll(request, id):
#     import zipfile
#     from io import StringIO
#     import os

#     datas = DataKlaim.objects.get(user__username=user.request, pk=id)
#     for data in datas:
#         nama = data.nama
#         file_kk = data.file_kk.file
#         file_ktp = data.file_ktp.file
#         file_buku_nikah = data.file_buku_nikah.file
#         file_lain = data.file_lain.file
#     filenames = [file_buku_nikah, file_kk, file_ktp, file_lain]
#     subdir = nama
#     zip_filename = "%s.zip" % subdir
#     s = StringIO()
#     zf = zipfile.ZipFile(s, "w")
#     for fpath in filenames:
#         fdir, fname = os.path.split(fpath)
#         zip_path = os.path.join(subdir, fname)
#         zf.write(fpath, zip_path)
#     zf.close()
#     resp = HttpResponse(s.getvalue(), mimetype="application/x-zip-compressed")
#     # ..and correct content-disposition
#     resp['Content-Disposition'] = 'attachment; filename=%s' % zip_filename

#     return resp

klaim_registration/templates/klaim_registration/daftar.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %}FORM INPUT DATABASE TK{% endblock  %}

{% block stylesheets %}

{% endblock  %}

{% block content %}
<main class="c-main">
    <div class="container-fluid">
        <div class="fade-in">
            <div class="row">
                <div class="col">
                    <form class="row m-2" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                        <div class="col-8">
                            <div class="card">
                                <div class="card-header">
                                    DATA TENAGA KERJA
                                </div>
                                
                                    <div class="card-body">
                                        <div class="row mb-2">
                                            <div class="col">
                                                {{forms.nama}}
                                                {{forms.nama.errors}}
                                            </div>
                                            <div class="col">
                                                {{forms.nik}}
                                                {{forms.nik.errors}}
                                            </div>
                                        </div>
                                        <div class="row mb-2">
                                            <div class="col">
                                                {{forms.tempat_lahir}}
                                                {{forms.tempat_lahir.errors}}
                                            </div>
                                            <div class="col">
                                                {{forms.tgl_lahir}}
                                                {{forms.tgl_lahir.errors}}
                                            </div>
                                        </div>
                                        <div class="row mb-2">
                                            <div class="col">
                                                {{forms.kpj}}
                                                {{forms.kpj.errors}}
                                            </div>
                                            <div class="col">
                                                {{forms.npp}}
                                                {{forms.npp.errors}}
                                            </div>
                                        </div>
                                        <div class="row mb-2">
                                            <div class="col">
                                                {{forms.nama_ibu}}
                                                {{forms.nama_ibu.errors}}
                                            </div>
                                            <div class="col">
                                                {{forms.status}}
                                                {{forms.status.errors}}
                                            </div>
                                        </div>
                                        <div class="row mb-2">
                                            <div class="col">
                                                {{forms.nama_rekening}}
                                            </div>
                                            <div class="col">
                                                {{forms.no_rekening}}
                                                {{forms.no_rekening.errors}}
                                            </div>
                                        </div>
                                        <div class="row mb-2">
                                            <div class="col">{{forms.no_hp}}{{forms.no_hp.errors}}
                                            <label class="form-label">Format nomor hp : 08xxxxxx</label>
                                            </div>
                                            
                                            <div class="col">
                                                {{forms.alamat}}
                                                {{forms.alamat.errors}}
                                            </div>
                                        </div>
                                        
                                    </div>

                                    <div class="card-header">
                                        DATA KELUARGA
                                    </div>
                                        <div name="pasangan" class="card-body">
                                            <div class="row mb-2">
                                                <div class="col">
                                                    {{forms.nama_pasangan}}
                                                    {{forms.nama_pasangan.errors}}
                                                </div>
                                                <div class="col">
                                                    {{forms.tgl_lahir_pasangan}}
                                                    {{forms.tgl_lahir_pasangan.errors}}
                                                </div>
                                            </div>
                                            <div class="row mb-2">
                                                <div class="col">
                                                    {{forms.nama_anak_s}}
                                                    {{forms.nama_anak_s.errors}}
                                                </div>
                                                <div class="col">
                                                    {{forms.tgl_lahir_s}}
                                                    {{forms.tgl_lahir_s.errors}}
                                                </div>
                                            </div>
                                            <div class="row mb-2">
                                                <div class="col">
                                                    {{forms.nama_anak_d}}
                                                    {{forms.nama_anak_d.errors}}
                                                </div>
                                                <div class="col">
                                                    {{forms.tgl_lahir_d}}
                                                    {{forms.tgl_lahir_d.errors}}
                                                </div>
                                            </div>
                                        </div>
                                
                            </div>
                        </div>
                        
                        <div class="col-8">
                            <div class="card">
                                <div class="card-header">
                                    UPLOAD BERKAS
                                </div>
                                <div class="card-body text-end">
                                    <div class="row mb-2">
                                        <div class="col">
                                            <label class="form-label">Upload Kartu Keluarga</label>
                                            {{forms.file_kk}}
                                            {{forms.file_kk.errors}}
                                        </div>
                                    </div>
                                    <div class="row mb-2">
                                        <div class="col">
                                            <label class="form-label">Upload KTP</label>
                                            {{forms.file_ktp}}
                                            {{forms.file_ktp.errors}}
                                        </div>
                                    </div>
                                    <div class="row mb-2">
                                        <div class="col">
                                            <label class="form-label">Upload Buku Nikah</label>
                                            {{forms.file_buku_nikah}}
                                            {{forms.file_buku_nikah.errors}}
                                        </div>
                                    </div>
                                    <div class="row mb-2">
                                        <div class="col">
                                            <label class="form-label">Upload File lain</label>
                                            {{forms.file_lain}}
                                            {{forms.file_lain.errors}}
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Daftarkan</button>
                                </div>
                            </div>
                        <div>
                        </div>
                        

                    </form>
                </div>
            </div>
        </div>
    </div>
</main>


{% endblock  %}


{% block javascripts %}
<script>
$(document).ready(function(){
    $('#id_npp').select2();
})
</script>

<script>
$(document).ready(function() {
    $('div[name="pasangan"]').hide();
    showhide();
    $("#id_status").change(function () {
        showhide();
    });
    
});

function showhide(){
      if( $('select[name="status"]').val() == 2){
            console.log('Menikah')
            $('div[name="pasangan"]').show();
        }
    else{
            $('div[name="pasangan"]').hide();
            console.log('Salah')
        }
}
</script>


{% endblock  %}

klaim_registration/templates/klaim_registration/hrdtest.html
{% extends 'base.html' %}

{% load static %}

{% block title %}FORM INPUT DATABASE TK JKM{% endblock  %}

{% block style %}

{% endblock  %}

{% block content %}
<h1>Test</h1>
<input type="text" id="test">
<table id="test-table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Hrd ID</th>
      <th>Keterangan</th>
      <th>Klaim ID</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
    </tr>
  </tbody>
</table>
{% endblock  %}


{% block script %}
<script type="text/javascript">

const urlKlaim = "{% url 'get-klaim-test' %}"
const testBox = document.getElementById('test')
const testTable = document.getElementById('test-table')


$.ajax({
  type:'GET',
  url:urlKlaim,
  success: function(response){
    console.log(response.data)
    const klaimData = response.data
    klaimData.map(item => {
      $("#test-table tbody").append("<tr><td>" + item.id + "</td><td>" + item.hrd_id + "</td><td>" + item.keterangan + "</td></tr>")
    })

  },
  error: function(error){
    console.log(error)
  }
})

$('#id_npp').select2({placeholder:'Pilih Perusahaan'});

</script>

{% endblock  %}

klaim_registration/templates/klaim_registration/index.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block tilte %}LIST DATA TK{% endblock  %}

{% block stylesheets %}


{% endblock  %}

{% block breadcrumb %}

{% endblock  %}
{% block content %}

{% for message in messages  %}
  <div class="alert alert-warning" role="alert">
  Anda sudah pernah melakuakn pengajuan. Silahkan
  <a class="alert-link" href="{% url 'logout' %}">Klik tulisan ini</a>
  untuk keluar .</div>
{% endfor %}

  <main class="c-main">
    <div class="container-fluid">
      <div class="fade-in">
        <div class="row">
          <div class="col-lg-xl">
            <div class="card">
              <div class="card-header"><i class="fa fa-align-justify"></i> Daftar Klaim</div>
              <div class="card-body">
              
  
  <table id="example" class="table table-responsive table-bordered table-striped table-sm">
      <thead>
          <tr>
          <th scope="col">#</th>
          <th scope="col">Nama</th>
          <th scope="col">KPJ</th>
          <th scope="col">Nama</br>Perusahaan</th>
          <th scope="col">Tempat/</br>Tgl.Lahir</th>
          <th scope="col">NIK</th>
          <th scope="col">Alamat</th>
          <th scope="col">Nama Ibu Kandung</th>
          <th scope="col">Status </br>Pernikahan</th>
          <th scope="col">No Rekening</th>
          <th scope="col">Kartu Keluarga</th>
          <th scope="col">KTP</th>
          <th scope="col">Buku Nikah</th>
          <th scope="col">Dokumen Lain</th>
          <th scope="col">Status</th>
          </tr>
    </thead>
    <tbody>
    {% for data in datas  %}
      <tr>
          <td>{{forloop.counter}}</td>
          <td>{{data.nama}}</td>
          <td>{{data.kpj}}</td>
          <td>{{data.npp}}</td>
          <td>{{data.tempat_lahir}}</br>{{data.tgl_lahir}}</td>
          <td>{{data.nik}}</td>
          <td>{{data.alamat}}</td>
          <td>{{data.nama_ibu}}</td>
          <td>{{data.get_status_display}}</td>
          <td>{{data.no_rekening}}</td>
          <td><a href="{{ data.file_kk.url }}" class="badge bg-info text-dark">Download</a></td>
          <td><a href="{{ data.file_ktp.url }}" class="badge bg-info text-dark">Download</a></td>
          <td><a href="{{ data.file_buku_nikah.url }}" class="badge bg-info text-dark">Download</a></td>
          {% if data.file_lain %}
            <td><a href="{{ data.file_lain.url }}" class="badge bg-info text-dark">Download</a></td>
          {% else %}
            <td>Belum Upload</td>
          {% endif %}
          {% if data.status_approve == 'DALAM PEMERIKSAAN' %}
            <td><span class="badge bg-info text-dark">DALAM PROSES</span></td>
          {% elif data.status_approve == 'DISETUJUI'%}
            <td><span class="badge bg-success">SETUJU</span></td>
          {% else %}
            <td><span class="badge bg-danger">DITOLAK</span></td>
          {% endif %}
          
      </tr>
    
    {% endfor %}
    
    </tbody>
  </table>


</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  <div class="form-group">
           
            <input class="form-control" id="size" type="hidden" value={{size}} >
        </div>
{% endblock  %}

{% block javascripts %}
<script>
$(document).ready(function() {
    
   var t = $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            {
                extend:'pdfHtml5',
                orientation: 'landscape',
                pageSize:'LEGAL'
            },
            {
                extend: 'excelHtml5',
                customize: function ( xlsx ){
                var size = document.getElementById('size').value
                console.log(size)
                
                var sheet = xlsx.xl.worksheets['sheet1.xml']
                for(i = 2;i<=size+2;i++){
                    
                // jQuery selector to add a border
                    $(`row c[r*="${i}"]`, sheet).attr( 's', '25' );
                }
            }
            }
        ],
        
        columnDefs: [ {
            "defaultContent": "-",
            sortable: false,
            "class": "number",
            
            targets: 0
        } ],
        order: [[ 8, 'asc' ]],
        fixedColumns:true
    } );
        
    t.on( 'order.dt search.dt', function () {
        t.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
            cell.innerHTML = i+1;
        } );
    } ).draw();
} );
</script>


{% endblock javascripts %}

klaim_registration/templates/klaim_registration/modal.html
<div class="modal fade" id="detailModal{{instance.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Approval {{data.klaim.nama}}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                Detail Tenaga Kerja {{instance.nama}}
                            </div>
                            <div class="card-body">
                                <div class="form-group row">
                                    <label class="col-md-3 col-form-label">Nama</label>
                                    <div class="col-md-9">
                                        <p class="form-control-static">{{instance.nama}}</p>
                                    </div>
                                <div>
                                <div class="form-group row">
                                    <label class="col-md-3 col-form-label">No. KTP/NIK</label>
                                    <div class="col-md-9">
                                        <p class="form-control-static">{{instance.nik}}</p>
                                    </div>
                                <div>
                                <div class="form-group row">
                                    <label class="col-md-3 col-form-label">Tempat/Tgl.Lahir</label>
                                    <div class="col-md-9">
                                        <p class="form-control-static">{{instance.tempat_lahir}}/{{instance.tgl_lahir}}</p>
                                    </div>
                                <div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
  </div>
</div>